Add Python version 3.12 specification
At least for me, only worked with 3.12 due to:

```
error: Distribution `onnxruntime==1.19.2 @ registry+https://pypi.org/simple` can't be installed because it doesn't have a source distribution or wheel for the current platform

hint: You're using CPython 3.13 (`cp313`), but `onnxruntime` (v1.19.2) only has wheels with the following Python ABI tags: `cp39`, `cp310`, `cp311`, `cp312`

```